[package]
name = "nist_policy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
openssl = "0.10.64"
regex = "1.10.4"
rusqlite = {version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tempfile = "3.10.1"
uuid = { version = "1.8.0", features = ["v4"] }
rev_lines = "0.3.0"