[package]
name = "nist_policy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
openssl = "0.10.62"
rusqlite = "0.30.0"
serde = "1.0.195"
serde_json = "1.0.111"
uuid = "1.6.1"
