[package]
name = "factory_use_case"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = {version = "0.3.6", features = ["tls"]}
tokio = {version = "1.36.0", features = ["rt", "macros"]}
rand = "0.8.5"