name: Build and Package Demo Server

on:
  release:
    types: [created, released]
  push:
    tags:
      - 'v0.0.1'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-arm64:
    name: Build ARM64 Server
    runs-on: ubuntu-latest
    container:
      image: ionutnqm/arm64-libs:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Debug Current Path and List Files
        run: |
          echo "Current directory:"
          pwd
          echo "List of files:"
          ls -l

      - name: Build ARM64 Server
        run: aarch64-linux-gnu-gcc -o server_arm64 debian-brski/brski-demo-app-deb/opt/demo-server/server.c -L/libmicrohttpd/src/microhttpd/.libs -L/zlib -lmicrohttpd -lz -static
   
      - name: Upload server binary as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-arm64-binary
          path: server_arm64
  
  build-x86_64:
    name: Build x86_64 Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update package lists
        run: sudo apt-get update

      - name: Install libmicrohttpd
        run: sudo apt-get install -y libmicrohttpd-dev

      - name: Create Directory for x86_64 Binary
        run: mkdir -p brski-demo-app-deb/opt/demo-server/

      - name: Build x86_64 Server
        run: gcc -o server_x86_64 debian-brski/brski-demo-app-deb/opt/demo-server/server.c -lmicrohttpd

      - name: List files after build
        run: |
          echo "Current directory for x86_64:"
          pwd
          echo "List of files:"
          ls -l

      - name: Rename x86_64 binary for packaging
        run: mv server_x86_64 brski-demo-app-deb/opt/demo-server/server_x86_64

      - name: Upload x86_64 server binary as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-x86_64-binary
          path: brski-demo-app-deb/opt/demo-server/server_x86_64
  
  package-deb:
    name: Package Debian
    runs-on: ubuntu-latest
    needs: [build-arm64, build-x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download ARM64 server binary
        uses: actions/download-artifact@v2
        with:
          name: server-arm64-binary
          path: debian-brski/

      - name: Download x86_64 server binary
        uses: actions/download-artifact@v2
        with:
          name: server-x86_64-binary
          path: debian-brski/

      - name: Build ARM64 Debian Package
        run: dpkg-deb --build brski-demo-app-deb brski-demo-app-deb_arm64.deb

      - name: Build x86_64 Debian Package
        run: dpkg-deb --build brski-demo-app-deb brski-demo-app-deb-x86_64.deb

      - name: Upload ARM64 .deb Package to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: brski-demo-app-deb-arm64
          path: brski-demo-app-deb_arm64.deb

      - name: Upload x86_64 .deb Package to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: brski-demo-app-deb-x86_64
          path: brski-demo-app-deb-x86_64.deb

  release-debs:
    name: Create Release and Upload Debian Packages
    runs-on: ubuntu-latest
    needs: [build-arm64, build-x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up release information
        id: release_info
        run: |
          echo "RELEASE_TAG=v0.0.1" >> $GITHUB_ENV
          echo "RELEASE_NAME=Brski-demo-app v0.0.1.alpha.0" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Download ARM64 Debian Package
        uses: actions/download-artifact@v2
        with:
          name: brski-demo-app-deb-arm64
          path: .

      - name: Download AMD64 Debian Package
        uses: actions/download-artifact@v2
        with:
          name: brski-demo-app-deb-x86_64
          path: .

      - name: Upload ARM64 Debian Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./brski-demo-app-deb_arm64.deb
          asset_name: brski-demo-app-deb_arm64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload AMD64 Debian Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./brski-demo-app-deb-x86_64.deb
          asset_name: brski-demo-app-deb-x86_64.deb
          asset_content_type: application/vnd.debian.binary-package

